version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Install Fn CLI
          command: curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
      - run:
          name: Build software
          command: |
            pushd get-joke
            fn build
            popd

