version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Fn CLI
          command: curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
      - run:
          name: Build software
          command: |
            pushd get-joke
            fn build
            popd
      - run:
          name: Store Oracle Cloud CLI private key
          command: echo ${OCI_PRIVATE_KEY} > oracle.pem
      - run:
          name: Prepare Oracle Cloud CLI
          command: |
            mkdir ~/.oci
            cat > ~/.oci/config << EOF
            [circleci]
            user=${OCI_USER_OCID}
            fingerprint=${OCI_KEY_FINGERPRINT}
            key_file=~/oracle.pem
            tenancy=${OCI_TENANCY_ID}
            region=fra
            pass_phrase=${OCI_PRIVATE_KEY_PASSWORD}
            EOF
      - run:
          name: Login to Oracle Cloud Infrastructure Registry
          command: |
            docker login fra.ocir.io -u ${OCIR_REPOSITORY}/circleci -p ${OCIR_TOKEN}
      - run:
          name: Publish functions
          command: |
            fn create context awesomesauce --provider oracle
            fn use context awesomesauce
            fn update context oracle.profile circleci
            fn update context oracle.compartment-id ${COMPARTMENT_OCID}
            fn update context oracle.tenancy-id ${OCI_TENANCY_ID}
            fn update context api-url https://functions.eu-frankfurt-1.oraclecloud.com
            fn update context registry fra.ocir.io/${OCIR_REPOSITORY}/dad-jokes
            fn deploy --app Dad-Jokes get-joke
      - run:
          name: Cleanup Oracle Cloud CLI private key
          command: rm ~/oracle.pem
