version: 2

workflows:
  version: 2
  build:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "14 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Fn CLI
          command: curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
      - run:
          name: Build software
          command: |
            pushd get-joke
            fn build
            popd
      - run:
          name: Login to Oracle Cloud Infrastructure Registry
          command: |
            docker login fra.ocir.io -u ${OCIR_REPOSITORY}/circleci -p ${OCIR_TOKEN}
      - run:
          name: Prepare publication of functions
          command: |
            fn create context awesomesauce-root --provider oracle
            fn use context awesomesauce-root
            fn update context oracle.compartment-id ${COMPARTMENT_OCID}
            fn update context oracle.tenancy-id ${OCI_TENANCY_ID}
            fn update context api-url https://functions.eu-frankfurt-1.oraclecloud.com
            fn update context registry fra.ocir.io/${OCIR_REPOSITORY}/dad-jokes
      - run:
          name: Publish Get Joke function
          command: |
            fn deploy --app Dad-Jokes get-joke
